"""The storage boundary.

Four methods, because four are what this system does to a stored file: put one
there, read it back when a parser needs it, ask whether it is there, and
remove it when the row that referenced it goes away. Anything else would be a
guess about a milestone that has not happened.

Everything the application knows about a file is its **key** — a relative,
server-generated path like `documents/<document_id>/<version_id>.pdf`. A key
is not a filesystem path: it is an identifier that some implementation
resolves. Keeping that distinction is what allows `storage_path` in the
database to survive the storage root being moved.

The Protocol exists so no filesystem call appears outside this package, not
because a second implementation is planned. There is one, and the
specification's "Postgres is the only datastore" rule means there is unlikely
ever to be a remote one.
"""

from dataclasses import dataclass
from typing import BinaryIO, Protocol, runtime_checkable


class StorageError(RuntimeError):
    """Something went wrong inside the storage layer.

    Carries a message for the log. Callers must not put it on the wire: the
    specification requires that error responses expose no filesystem paths,
    and the honest place for a path is the operator's log.
    """


class UnsafeKey(StorageError):
    """A key that does not resolve to a place this storage may write.

    Absolute, containing `..`, or escaping the root. Keys are generated by
    this application from UUIDs, so a caller that trips this has a bug rather
    than a bad file — but the check is here because the cost of being wrong
    once is a write outside the root.
    """


@dataclass(frozen=True)
class StoredFile:
    """What a completed write produced."""

    key: str
    size: int


@runtime_checkable
class Storage(Protocol):
    """Where uploaded files live."""

    def write(self, key: str, source: BinaryIO) -> StoredFile:
        """Store `source` at `key`, atomically, and report what was stored.

        Atomic in the sense that matters: no reader ever sees a partial file
        at `key`. An interrupted write leaves either nothing or the whole
        thing, never half.
        """
        ...

    def open(self, key: str) -> BinaryIO:
        """Read a stored file back."""
        ...

    def delete(self, key: str) -> None:
        """Remove a stored file. Removing one that is not there is not an error."""
        ...

    def exists(self, key: str) -> bool:
        """Whether anything is stored at `key`."""
        ...


__all__ = ["Storage", "StorageError", "StoredFile", "UnsafeKey"]
